language: php

php:
  - 7.3
  - nightly

install:
  composer install

script:
  - |
    cd $TRAVIS_BUILD_DIR/tools && php createstatic.php
    
    if([ $TRAVIS_PHP_VERSION == "7.3" ] && [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ])
    then
      cd $TRAVIS_BUILD_DIR/tools && php uploadToS3.php
      echo "Deployed"
    fi
