## AWS IAM permissions in use for CI
#
#{
#    "Version": "2012-10-17",
#    "Statement": [
#        {
#            "Effect": "Allow",
#            "Action": "s3:*",
#            "Resource": [
#                "arn:aws:s3:::tech.mayhew.io/*",
#                "arn:aws:s3:::tech.mayhew.io"
#            ]
#        },
#        {
#            "Effect": "Allow",
#            "Action": [
#                "cloudfront:CreateInvalidation"
#            ],
#            "Resource": "arn:aws:cloudfront::ACCOUNTID:distribution/DISTRIBUTIONID"
#        },
#        {
#            "Effect": "Allow",
#            "Action": [
#                "cloudfront:ListDistributions"
#            ],
#            "Resource": "*"
#        }
#    ]
#}

language: php

php:
  - 7.3
  - nightly

install:
  composer install

script:
  - |
    cd $TRAVIS_BUILD_DIR/tools && php createstatic.php
    
    if([ $TRAVIS_PHP_VERSION == "7.3" ] && [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ])
    then
      cd $TRAVIS_BUILD_DIR/tools && php uploadToS3.php
      echo "Deployed"
    fi
